version: '3'

services:
  auth-service:
    build:
      dockerfile: ./Dockerfile
      context: AuthenticationService
    image: auth-service
    container_name: auth-service
    ports:
      - "8080:8080"