spring:
  application:
    name: Authentication-Service
  jpa:
    show-sql: true
  datasource:
#    Серверная база данных
#    url: jdbc:postgresql://my-teamup.ru:5432/TeamUp
#    username: TeamUp
#    password: guewhprihdfjhsargoheusdweufhui2389yf2uy892f3
#    driver-class-name: org.postgresql.Driver

#    Локальная база данных
    url: jdbc:postgresql://localhost:5432/TeamUp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: my.teamup.platform@gmail.com
    password: pkfqcauuhwmitfzg
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

logging:
  level:
    web: debug

server:
  port: 8081

token:
  secret:
    key: aEJngisbX3ZhpiMn/GgZws1/QftesQZi9EC/5Uwf+as=