spring:
  application:
    name: TeamUp-Gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

token:
  secret:
    key: aEJngisbX3ZhpiMn/GgZws1/QftesQZi9EC/5Uwf+as=

logging:
  level:
    web: debug

server:
  port: 8080
