spring:
  application:
    name: Migration-Service
  datasource:
    url: jdbc:postgresql://my-teamup.ru:5432/TeamUp
    username: TeamUp
    password: guewhprihdfjhsargoheusdweufhui2389yf2uy892f3
    driver-class-name: org.postgresql.Driver

server:
  port: 8100
